#!/bin/sh

P_HIST="$(clipster -c -o -n 500 --nul)"

F_HIST="$(echo "$P_HIST" | awk -vRS=$'\0' 'BEGIN { FS="\n"; OFS=" " } { $1=$1; print $0 }' | sed 's/^ *//' | sed '/^\s*$/d' | awk '{printf("%003d %s\n", NR, $0)}')"

SELECTION="$(echo "$F_HIST" | rofi -dmenu -lines 20 -width 80 -p 'selection: ')"

NUMBER="$(echo "$SELECTION" | cut -c1-3 | sed 's/^0*//')"

EXACT_SELECTION="$(echo "$P_HIST" | awk -vRS=$'\0' "NR == $NUMBER { print; exit }")"

echo "$EXACT_SELECTION" | xsel --clipboard
