#!/bin/sh

C_HIST="$(clipster -c -o -n 500 -0 | gawk 'BEGIN {RS = "\0"; FS="\n"; OFS=" " } { $1=$1; print $0 }' | sed 's/^ *//' | sed '/^\s*$/d' | gawk '{printf("%003d %s\n", NR, $0)}')"

SELECTION="$(echo "$C_HIST" | rofi -dmenu -lines 20 -width 80 -p 'selection: ')"

NUMBER="$(echo "$SELECTION" | cut -c1-3 | sed 's/^0*//')"
((NUMBER++))

EXACT_SELECTION="$(clipster -c -o -n 500 -0 | gawk 'BEGIN {RS = "\0"}'"NR == $NUMBER { print; exit }")"

echo "$EXACT_SELECTION" | xsel --clipboard
